<Configs>
  <Config Type="WEB" Active="False" SystemConfig="True" Product="DTS80" Name="Toshiba Warranty Info" Description="">
    <URLBase User="" Url="https://support.dynabook.com/warranty" Encrypted="True" Password="" Anonymous="True" ProxyHost="" ProxyPort="80" UseProxy="False" UseIE="True" IEEmulation="False" UseMacro="False" ProxyUser="" ProxyDomain="" ProxyPassword="" USFormat="False" Timeout="60" Retries="0" Product="MANAGEMENTSUITE" AssetComp="" Group="">
  <Forms>
    <Form Querystring="False" SubmitType="button" SubmitField="id" SubmitValue="getWarrantyInfoBtn" SubmitForm="" SubmitTag="input" UseButton="True" AllValues="False" JustLoad="False" CookiesString="" DeleteCookies="False" WaitAfterLoad="True" WaitText="id=servicePrograms" WaitSeconds="30" WaitFirst="True" WaitFirstText="getWarrantyInfoBtn" WaitFirstSeconds="30" PerformAnotherPostBack="False" JustWait="False" InnerText="False" NewUrl="" Macro="" CheckImmediate="False">
      <Fields>
        <Field Name="serialNo" Attribute="Computer.System.Serial Number" Static="FALSE" Contains="FALSE" Checked="FALSE" FieldType="text" Password="FALSE" Value="" WaitSecs="0" />
      </Fields>
      <Conditions>
        <Condition SearchText="&lt;div class=&quot;warranty_table right&quot; id=&quot;servicePrograms&quot; style=&quot;display: none;&quot;" ReturnError="False" ReturnErrorText="">
          <Forms>
            <Form Querystring="False" SubmitType="" SubmitField="" SubmitValue="" SubmitForm="" SubmitTag="input" UseButton="False" AllValues="False" JustLoad="True" CookiesString="" DeleteCookies="False" WaitAfterLoad="False" WaitText="" WaitSeconds="30" WaitFirst="False" WaitFirstText="" WaitFirstSeconds="5" PerformAnotherPostBack="False" JustWait="False" InnerText="False" NewUrl="" Macro="" CheckImmediate="False">
              <Fields />
              <Conditions />
              <Returns>
                <Return RegExp="False" Search="" Return="" Table="0" Row="0" Column="0" RowsAfter="False" TablesAfter="False" ReturnMany="False" Attribute="Computer.Warranties.Warranty.Start date" Skip="0" Sort="False" SortBy="Smallest" TableSearch="False" TableText="" Header="id=&quot;productInformation&quot;" VBScript="retvalue = CDate(value)" SearchString="True" HeaderCI="True" Find="&lt;Table" FindCI="True" LookFor="&lt;TD" LookForCI="True" LooForNum="6" LookDirection="True" Advance="&gt;" AdvanceCI="False" AdvanceNum="1" Capture="&lt;/TD" CaptureCI="True" HeaderOnce="False" EndAt="" />
                <Return RegExp="False" Search="" Return="" Table="0" Row="0" Column="0" RowsAfter="False" TablesAfter="False" ReturnMany="False" Attribute="Computer.Warranties.Ship Date" Skip="0" Sort="False" SortBy="Smallest" TableSearch="False" TableText="" Header="id=&quot;productInformation&quot;" VBScript="retvalue = Cdate(value)" SearchString="True" HeaderCI="True" Find="&lt;Table" FindCI="True" LookFor="&lt;TD" LookForCI="True" LooForNum="6" LookDirection="True" Advance="&gt;" AdvanceCI="False" AdvanceNum="1" Capture="&lt;/TD" CaptureCI="True" HeaderOnce="False" EndAt="" />
                <Return RegExp="False" Search="" Return="" Table="0" Row="0" Column="0" RowsAfter="False" TablesAfter="False" ReturnMany="False" Attribute="Computer.Warranties.Warranty.Title" Skip="0" Sort="False" SortBy="Smallest" TableSearch="False" TableText="" Header="id=&quot;productInformation&quot;" VBScript="retvalue = Trim(value)&#xD;&#xA;if instr(retvalue, &quot;&lt;&quot;) &gt; 0 then&#xD;&#xA;	retvalue = Mid(retvalue, instr(retvalue, &quot;&gt;&quot;) + 1)&#xD;&#xA;	retvalue = Mid(retvalue, 1, instr(retvalue, &quot;&lt;&quot;) -1)&#xD;&#xA;end if&#xD;&#xA;" SearchString="True" HeaderCI="True" Find="&lt;TABLE" FindCI="True" LookFor="&lt;TD" LookForCI="True" LooForNum="9" LookDirection="True" Advance="&gt;" AdvanceCI="False" AdvanceNum="1" Capture="&lt;/TD" CaptureCI="True" HeaderOnce="False" EndAt="" />
                <Return RegExp="False" Search="" Return="" Table="0" Row="0" Column="0" RowsAfter="False" TablesAfter="False" ReturnMany="False" Attribute="Computer.Warranties.Warranty.Description" Skip="0" Sort="False" SortBy="Smallest" TableSearch="False" TableText="" Header="id=&quot;productInformation&quot;" VBScript="" SearchString="True" HeaderCI="True" Find="&lt;TABLE" FindCI="True" LookFor="&lt;TD" LookForCI="True" LooForNum="11" LookDirection="True" Advance="&gt;" AdvanceCI="False" AdvanceNum="1" Capture="&lt;/TD" CaptureCI="True" HeaderOnce="False" EndAt="" />
                <Return RegExp="False" Search="" Return="" Table="0" Row="0" Column="0" RowsAfter="False" TablesAfter="False" ReturnMany="False" Attribute="Computer.Warranties.Warranty.End date" Skip="0" Sort="False" SortBy="Smallest" TableSearch="False" TableText="" Header="id=&quot;productInformation&quot;" VBScript="retvalue = CDate(value)" SearchString="True" HeaderCI="True" Find="&lt;Table" FindCI="True" LookFor="&lt;TD" LookForCI="True" LooForNum="10" LookDirection="True" Advance="&gt;" AdvanceCI="False" AdvanceNum="1" Capture="&lt;/TD" CaptureCI="True" HeaderOnce="False" EndAt="" />
              </Returns>
            </Form>
          </Forms>
        </Condition>
        <Condition SearchText="id=servicePrograms" ReturnError="False" ReturnErrorText="">
          <Forms>
            <Form Querystring="False" SubmitType="" SubmitField="" SubmitValue="" SubmitForm="" SubmitTag="input" UseButton="False" AllValues="False" JustLoad="True" CookiesString="" DeleteCookies="False" WaitAfterLoad="False" WaitText="" WaitSeconds="30" WaitFirst="True" WaitFirstText="id=&quot;servicePrograms&quot;" WaitFirstSeconds="60" PerformAnotherPostBack="False" JustWait="False" InnerText="False" NewUrl="" Macro="" CheckImmediate="False">
              <Fields />
              <Conditions />
              <Returns>
                <Return RegExp="False" Search="" Return="" Table="0" Row="0" Column="0" RowsAfter="False" TablesAfter="False" ReturnMany="True" Attribute="Computer.Warranties.Warranty.Description" Skip="0" Sort="False" SortBy="Smallest" TableSearch="False" TableText="" Header="id=servicePrograms" VBScript="retvalue = replace(value, &quot;&amp;amp;&quot;, &quot;&amp;&quot;)" SearchString="True" HeaderCI="False" Find="&lt;TABLE" FindCI="True" LookFor="&lt;TD" LookForCI="True" LooForNum="1" LookDirection="True" Advance="&gt;" AdvanceCI="False" AdvanceNum="1" Capture="&lt;/TD" CaptureCI="True" HeaderOnce="True" EndAt="" />
                <Return RegExp="False" Search="" Return="" Table="0" Row="0" Column="0" RowsAfter="False" TablesAfter="False" ReturnMany="True" Attribute="Computer.Warranties.Warranty.Start date" Skip="0" Sort="False" SortBy="Smallest" TableSearch="False" TableText="" Header="id=servicePrograms" VBScript="retvalue = CDate(value)" SearchString="True" HeaderCI="True" Find="&lt;TABLE" FindCI="True" LookFor="&lt;TD" LookForCI="True" LooForNum="2" LookDirection="True" Advance="&gt;" AdvanceCI="True" AdvanceNum="1" Capture="&lt;/TD" CaptureCI="True" HeaderOnce="True" EndAt="" />
                <Return RegExp="False" Search="" Return="" Table="0" Row="0" Column="0" RowsAfter="False" TablesAfter="False" ReturnMany="True" Attribute="Computer.Warranties.Warranty.End date" Skip="0" Sort="True" SortBy="Largest" TableSearch="False" TableText="" Header="id=servicePrograms" VBScript="retvalue= CDate(value)" SearchString="True" HeaderCI="True" Find="&lt;TABLE" FindCI="True" LookFor="&lt;TD" LookForCI="True" LooForNum="3" LookDirection="True" Advance="&gt;" AdvanceCI="False" AdvanceNum="1" Capture="&lt;/TD" CaptureCI="True" HeaderOnce="True" EndAt="" />
              </Returns>
            </Form>
          </Forms>
        </Condition>
        <Condition SearchText="id=&quot;servicePrograms&quot;" ReturnError="False" ReturnErrorText="">
          <Forms>
            <Form Querystring="False" SubmitType="" SubmitField="" SubmitValue="" SubmitForm="" SubmitTag="input" UseButton="False" AllValues="False" JustLoad="True" CookiesString="" DeleteCookies="False" WaitAfterLoad="False" WaitText="" WaitSeconds="30" WaitFirst="False" WaitFirstText="" WaitFirstSeconds="5" PerformAnotherPostBack="False" JustWait="False" InnerText="False" NewUrl="" Macro="" CheckImmediate="False">
              <Fields />
              <Conditions />
              <Returns>
                <Return RegExp="False" Search="" Return="" Table="0" Row="0" Column="0" RowsAfter="False" TablesAfter="False" ReturnMany="True" Attribute="Computer.Warranties.Warranty.Description" Skip="0" Sort="False" SortBy="Smallest" TableSearch="False" TableText="" Header="id=&quot;servicePrograms&quot;" VBScript="retvalue = replace(value, &quot;&amp;amp;&quot;, &quot;&amp;&quot;)" SearchString="True" HeaderCI="True" Find="&lt;TABLE" FindCI="True" LookFor="&lt;TD" LookForCI="True" LooForNum="1" LookDirection="True" Advance="&gt;" AdvanceCI="False" AdvanceNum="1" Capture="&lt;/TD" CaptureCI="True" HeaderOnce="True" EndAt="" />
                <Return RegExp="False" Search="" Return="" Table="0" Row="0" Column="0" RowsAfter="False" TablesAfter="False" ReturnMany="True" Attribute="Computer.Warranties.Warranty.Start date" Skip="0" Sort="False" SortBy="Smallest" TableSearch="False" TableText="" Header="id=&quot;servicePrograms&quot;" VBScript="retvalue = CDate(value)" SearchString="True" HeaderCI="True" Find="&lt;TABLE" FindCI="True" LookFor="&lt;TD" LookForCI="True" LooForNum="2" LookDirection="True" Advance="&gt;" AdvanceCI="True" AdvanceNum="1" Capture="&lt;/TD" CaptureCI="True" HeaderOnce="True" EndAt="" />
                <Return RegExp="False" Search="" Return="" Table="0" Row="0" Column="0" RowsAfter="False" TablesAfter="False" ReturnMany="True" Attribute="Computer.Warranties.Warranty.End date" Skip="0" Sort="True" SortBy="Largest" TableSearch="False" TableText="" Header="id=&quot;servicePrograms&quot;" VBScript="retvalue= CDate(value)" SearchString="True" HeaderCI="True" Find="&lt;TABLE" FindCI="True" LookFor="&lt;TD" LookForCI="True" LooForNum="3" LookDirection="True" Advance="&gt;" AdvanceCI="False" AdvanceNum="1" Capture="&lt;/TD" CaptureCI="True" HeaderOnce="True" EndAt="" />
              </Returns>
            </Form>
          </Forms>
        </Condition>
      </Conditions>
      <Returns>
        <Return RegExp="False" Search="" Return="" Table="0" Row="0" Column="0" RowsAfter="False" TablesAfter="False" ReturnMany="False" Attribute="Computer.Warranties.Warranty.Start date" Skip="0" Sort="False" SortBy="Smallest" TableSearch="False" TableText="" Header="id=&quot;productInformation&quot;" VBScript="retvalue = CDate(value)" SearchString="True" HeaderCI="True" Find="&lt;Table" FindCI="True" LookFor="&lt;TD" LookForCI="True" LooForNum="6" LookDirection="True" Advance="&gt;" AdvanceCI="False" AdvanceNum="1" Capture="&lt;/TD" CaptureCI="True" HeaderOnce="False" EndAt="" />
        <Return RegExp="False" Search="" Return="" Table="0" Row="0" Column="0" RowsAfter="False" TablesAfter="False" ReturnMany="False" Attribute="Computer.Warranties.Ship Date" Skip="0" Sort="False" SortBy="Smallest" TableSearch="False" TableText="" Header="id=&quot;productInformation&quot;" VBScript="retvalue = Cdate(value)" SearchString="True" HeaderCI="True" Find="&lt;Table" FindCI="True" LookFor="&lt;TD" LookForCI="True" LooForNum="6" LookDirection="True" Advance="&gt;" AdvanceCI="False" AdvanceNum="1" Capture="&lt;/TD" CaptureCI="True" HeaderOnce="False" EndAt="" />
        <Return RegExp="False" Search="" Return="" Table="0" Row="0" Column="0" RowsAfter="False" TablesAfter="False" ReturnMany="False" Attribute="Computer.Warranties.Warranty.Title" Skip="0" Sort="False" SortBy="Smallest" TableSearch="False" TableText="" Header="id=&quot;productInformation&quot;" VBScript="retvalue = Trim(value)&#xD;&#xA;if instr(retvalue, &quot;&lt;&quot;) &gt; 0 then&#xD;&#xA;	retvalue = Mid(retvalue, instr(retvalue, &quot;&gt;&quot;) + 1)&#xD;&#xA;	retvalue = Mid(retvalue, 1, instr(retvalue, &quot;&lt;&quot;) -1)&#xD;&#xA;end if&#xD;&#xA;" SearchString="True" HeaderCI="True" Find="&lt;TABLE" FindCI="True" LookFor="&lt;TD" LookForCI="True" LooForNum="9" LookDirection="True" Advance="&gt;" AdvanceCI="False" AdvanceNum="1" Capture="&lt;/TD" CaptureCI="True" HeaderOnce="False" EndAt="" />
        <Return RegExp="False" Search="" Return="" Table="0" Row="0" Column="0" RowsAfter="False" TablesAfter="False" ReturnMany="False" Attribute="Computer.Warranties.Warranty.Description" Skip="0" Sort="False" SortBy="Smallest" TableSearch="False" TableText="" Header="id=&quot;productInformation&quot;" VBScript="" SearchString="True" HeaderCI="True" Find="&lt;TABLE" FindCI="True" LookFor="&lt;TD" LookForCI="True" LooForNum="11" LookDirection="True" Advance="&gt;" AdvanceCI="False" AdvanceNum="1" Capture="&lt;/TD" CaptureCI="True" HeaderOnce="False" EndAt="" />
        <Return RegExp="False" Search="" Return="" Table="0" Row="0" Column="0" RowsAfter="False" TablesAfter="False" ReturnMany="False" Attribute="Computer.Warranties.Warranty.End date" Skip="0" Sort="False" SortBy="Smallest" TableSearch="False" TableText="" Header="id=&quot;productInformation&quot;" VBScript="retvalue = CDate(value)" SearchString="True" HeaderCI="True" Find="&lt;Table" FindCI="True" LookFor="&lt;TD" LookForCI="True" LooForNum="10" LookDirection="True" Advance="&gt;" AdvanceCI="False" AdvanceNum="1" Capture="&lt;/TD" CaptureCI="True" HeaderOnce="False" EndAt="" />
      </Returns>
    </Form>
  </Forms>
  <Returns />
</URLBase>
  </Config>
</Configs>